DEFAULT_ENV: dict[str, str] = {
    'SERVER_NAME': 'My VPN',
    'DOWNLOAD_URL': 'https://m-1-14-3w5hsuiikq-ez.a.run.app/ru/downloads',
    'PUBLIC_HOST': '',
    'SUPPORT_USERNAME': '',
    'AWG_I1': '<r 2><b 0x858000010001000000000669636c6f756403636f6d0000010001c00c000100010000105a00044d583737>',
    'AWG_PROTOCOL_VERSION': '2',
    'AWG_TRANSPORT_PROTO': 'udp',
    'DOCKER_CONTAINER': 'amnezia-awg2',
    'WG_INTERFACE': 'awg0',
    'DB_PATH': 'vpn_bot.db',
    'VPN_SUBNET_PREFIX': '10.8.1.',
    'FIRST_CLIENT_OCTET': '3',
    'MAX_CLIENT_OCTET': '254',
    'CONFIGS_PER_USER': '2',
    'CLEANUP_INTERVAL_SECONDS': '300',
    'PRIMARY_DNS': '1.1.1.1',
    'SECONDARY_DNS': '1.0.0.1',
    'CLIENT_MTU': '1376',
    'PERSISTENT_KEEPALIVE': '25',
    'CLIENT_ALLOWED_IPS': '0.0.0.0/0, ::/0',
    'STARS_PRICE_7_DAYS': '21',
    'STARS_PRICE_30_DAYS': '50',
    'STARS_PRICE_90_DAYS': '140',
    'PURCHASE_CLICK_COOLDOWN_SECONDS': '2',
    'PURCHASE_RATE_LIMIT_TTL_SECONDS': '3600',
    'USER_REISSUE_COOLDOWN_SECONDS': '600',
    'ADMIN_COMMAND_COOLDOWN_SECONDS': '2',
    'DOCKER_RETRIES': '3',
    'DOCKER_RETRY_BASE_DELAY': '0.5',
    'DOCKER_TIMEOUT_SECONDS': '20',
    'AWG_HELPER_PATH': '/usr/local/libexec/awg-bot-helper',
    'AWG_HELPER_USE_SUDO': '1',
    'AWG_HELPER_POLICY_PATH': '/etc/awg-bot-helper.json',
    'AWG_PEERS_CACHE_TTL_SECONDS': '5.0',
    'PENDING_KEY_TTL_SECONDS': '900',
    'PAYMENT_RETRY_DELAY_SECONDS': '60',
    'PAYMENT_PROVISIONING_LEASE_SECONDS': '180',
    'PAYMENT_MAX_ATTEMPTS': '5',
    'BROADCAST_BATCH_SIZE': '20',
    'BROADCAST_BATCH_DELAY_SECONDS': '0.2',
    'RECONCILIATION_INTERVAL_SECONDS': '45',
    'QOS_ENABLED': '1',
    'DEFAULT_KEY_RATE_MBIT': '100',
    'QOS_STRICT': '0',
    'REFERRAL_ENABLED': '1',
    'REFERRAL_INVITEE_BONUS_DAYS': '5',
    'REFERRAL_INVITER_BONUS_DAYS': '3',
    'EGRESS_DENYLIST_ENABLED': '0',
    'EGRESS_DENYLIST_DOMAINS': (
        'gosuslugi.ru,www.gosuslugi.ru,esia.gosuslugi.ru,pos.gosuslugi.ru,gosweb.gosuslugi.ru,'
        'госуслуги.рф,rkn.gov.ru,pd.rkn.gov.ru,service.rkn.gov.ru,nalog.gov.ru,www.nalog.gov.ru,'
        'lkfl2.nalog.ru,fssp.gov.ru,www.fssp.gov.ru,mvd.ru,www.mvd.ru,мвд.рф,gibdd.ru,www.gibdd.ru,'
        'sfr.gov.ru,pfr.gov.ru,rosreestr.gov.ru,www.rosreestr.gov.ru,goszakaz.gov.ru,zakupki.gov.ru,'
        'pravo.gov.ru,max.ru,www.max.ru'
    ),
    'EGRESS_DENYLIST_CIDRS': '',
    'EGRESS_DENYLIST_REFRESH_MINUTES': '30',
    'EGRESS_DENYLIST_MODE': 'strict',
    'TORRENT_POLICY_TEXT_ENABLED': '1',
    'AWG_JC': '6',
    'AWG_JMIN': '10',
    'AWG_JMAX': '50',
    'AWG_S1': '37',
    'AWG_S2': '98',
    'AWG_S3': '47',
    'AWG_S4': '14',
    'AWG_H1': '1486401722-1692300209',
    'AWG_H2': '1696990121-1817276760',
    'AWG_H3': '1841833217-1995591429',
    'AWG_H4': '2109962185-2145796739',
    'AWG_I2': '',
    'AWG_I3': '',
    'AWG_I4': '',
    'AWG_I5': '',
    'IGNORE_PEERS': '',
}
