"""
Platega payment integration for VPN bot.
Uses plategaio (async SDK) for non-blocking operations.
"""
import sys
import os
from typing import Optional, Dict, Any
from datetime import timedelta

# Добавляем путь к async SDK если он еще не в path
_sdk_async_path = os.path.join(os.path.dirname(__file__), '..', 'plategaio-main')
if _sdk_async_path not in sys.path:
    sys.path.insert(0, _sdk_async_path)

try:
    from plategaio import PlategaAsyncClient, CreateTransactionRequest, PaymentDetails
    PLATEGAIO_AVAILABLE = True
except ImportError as e:
    PLATEGAIO_AVAILABLE = False
    logger.error(f"Failed to import plategaio: {e}")

from aiogram import Bot, types
from aiogram.utils.keyboard import InlineKeyboardBuilder

from config import logger
from database import save_payment, upsert_payment_precheck, update_payment_status, get_payment_status

# Payment method constants from Platega
PLATEGA_METHOD_SBP_QR = 2
PLATEGA_METHOD_CARDS_RUB = 10

# Platega payment statuses
PLATEGA_STATUS_PENDING = "PENDING"
PLATEGA_STATUS_CONFIRMED = "CONFIRMED"
PLATEGA_STATUS_CANCELED = "CANCELED"
PLATEGA_STATUS_CHARGEBACKED = "CHARGEBACKED"


class PlategaPaymentService:
    """Service for handling Platega payments."""
    
    def __init__(self, merchant_id: str, secret: str, base_url: str = "https://app.platega.io"):
        self.merchant_id = merchant_id
        self.secret = secret
        self.base_url = base_url
        
        if not PLATEGAIO_AVAILABLE:
            logger.error("plategaio library not available - payments will not work")
    
    async def create_payment(
        self,
        amount: float,
        currency: str,
        description: str,
        payload: str,
        return_url: Optional[str] = None,
        failed_url: Optional[str] = None,
        payment_method: int = PLATEGA_METHOD_SBP_QR,
    ) -> Dict[str, Any]:
        """Create a new Platega payment transaction.
        
        Note: According to Platega API documentation, the transaction ID is generated
        automatically by the system - we do NOT send the 'id' field in the request.
        
        Args:
            amount: Payment amount
            currency: Currency code (e.g., 'RUB')
            description: Payment description
            payload: Custom payload (order_id in format user_id:sub_type) - returned in callback
            return_url: Success redirect URL (optional)
            failed_url: Failed redirect URL (optional)
            payment_method: Payment method constant (default: SBP QR)
        
        Returns:
            dict with transaction_id, redirect_url, status, expires_in
            
        Raises:
            RuntimeError: If plategaio is not available or API call fails
        """
        if not PLATEGAIO_AVAILABLE:
            raise RuntimeError("plategaio library not available")
        
        async with PlategaAsyncClient(
            merchant_id=self.merchant_id,
            secret=self.secret,
            base_url=self.base_url,
        ) as client:
            # Do NOT pass 'id' field - it's generated by Platega automatically
            tx_request = CreateTransactionRequest(
                payment_method=payment_method,
                payment_details=PaymentDetails(amount=amount, currency=currency),
                description=description,
                return_url=return_url,
                failed_url=failed_url,
                payload=payload,
            )
            response = await client.create_transaction(tx_request)
            
            return {
                "transaction_id": response.transaction_id,
                "redirect_url": response.redirect,
                "status": response.status,
                "expires_in": response.expires_in,
            }
    
    async def check_payment_status(self, transaction_id: str) -> Dict[str, Any]:
        """Check the status of a Platega payment.
        
        Args:
            transaction_id: Transaction ID from Platega
            
        Returns:
            dict with id, status, amount, currency, payment_method, redirect
            
        Raises:
            RuntimeError: If plategaio is not available or API call fails
        """
        if not PLATEGAIO_AVAILABLE:
            raise RuntimeError("plategaio library not available")
        
        async with PlategaAsyncClient(
            merchant_id=self.merchant_id,
            secret=self.secret,
            base_url=self.base_url,
        ) as client:
            status_response = await client.get_transaction_status(transaction_id)
            
            return {
                "id": status_response.id,
                "status": status_response.status,
                "amount": status_response.payment_details.get("amount"),
                "currency": status_response.payment_details.get("currency"),
                "payment_method": status_response.payment_method,
                "redirect": getattr(status_response, 'redirect', None),
            }
    
    @staticmethod
    def is_success_status(status: str) -> bool:
        """Check if payment status indicates successful payment."""
        return status == PLATEGA_STATUS_CONFIRMED
    
    @staticmethod
    def is_pending_status(status: str) -> bool:
        """Check if payment is still pending."""
        return status == PLATEGA_STATUS_PENDING
    
    @staticmethod
    def is_failed_status(status: str) -> bool:
        """Check if payment failed or was canceled."""
        return status in (PLATEGA_STATUS_CANCELED, PLATEGA_STATUS_CHARGEBACKED)


def get_platega_payment_keyboard(transaction_id: str, tariff_label: str) -> types.InlineKeyboardMarkup:
    """Generate keyboard with Platega payment button."""
    builder = InlineKeyboardBuilder()
    builder.button(
        text=f"💳 Оплатить {tariff_label} через СБП",
        callback_data=f"platega_pay:{transaction_id}"
    )
    builder.button(
        text="🔄 Проверить статус оплаты",
        callback_data=f"platega_check:{transaction_id}"
    )
    builder.button(
        text="⬅️ Назад к тарифам",
        callback_data="show_buy_menu"
    )
    return builder.as_markup()


def get_payment_method_selection_kb(tariff_payload: str, stars_price: int, rub_price: float) -> types.InlineKeyboardMarkup:
    """Generate keyboard for selecting payment method (Stars vs Platega)."""
    builder = InlineKeyboardBuilder()
    
    # Stars button
    builder.button(
        text=f"⭐ Telegram Stars ({stars_price}⭐)",
        callback_data=f"pay_stars:{tariff_payload}"
    )
    
    # Platega SBP button
    builder.button(
        text=f"💳 СБП ({rub_price}₽)",
        callback_data=f"pay_platega:{tariff_payload}"
    )
    
    builder.button(
        text="⬅️ Назад в профиль",
        callback_data="open_profile"
    )
    
    builder.adjust(1)  # One button per row
    return builder.as_markup()
