BTN_PROFILE = "👤 Профиль"
BTN_CONFIGS = "🔑 Подключение"
BTN_BUY = "💳 Оплатить доступ"
BTN_GUIDE = "📖 Как подключиться"
BTN_SUPPORT = "🆘 Поддержка"
BTN_REFERRALS = "🎁 Рефералы"
BTN_ADMIN = "⚙️ Админка"

ADMIN_CALLBACK_PREFIX = "a:"
USER_CONFIG_CALLBACK_PREFIX = "config_"

CB_BUY_7 = "buy_7"
CB_BUY_30 = "buy_30"
CB_BUY_90 = "buy_90"
CB_SHOW_INSTRUCTION = "show_instruction"
CB_SHOW_BUY_MENU = "show_buy_menu"
CB_CHECK_ACTIVATION_STATUS = "check_activation_status"
CB_CONFIG_DEVICE_PREFIX = "config_device_"
CB_CONFIG_CONF_PREFIX = "config_conf_"
CB_OPEN_CONFIGS = "open_configs"
CB_USER_REISSUE_CONFIRM = "user_reissue_confirm"
CB_USER_REISSUE_CANCEL = "user_reissue_cancel"
CB_USER_REISSUE_DEVICE_PREFIX = "user_reissue_device_"
CB_OPEN_SUPPORT = "open_support"
CB_SUPPORT_PAYMENT = "support_payment"
CB_SUPPORT_CONNECTION = "support_connection"
CB_SUPPORT_TERMS = "support_terms"
CB_SUPPORT_BACK = "support_back"

CB_ADMIN_LIST = "admin_list"
CB_ADMIN_STATS = "admin_stats"
CB_ADMIN_SYNC = "admin_sync_awg"
CB_ADMIN_BROADCAST = "admin_broadcast"
CB_ADMIN_COMMANDS = "admin_manual_commands"
CB_ADMIN_PRICES = "admin_prices"
CB_ADMIN_PRICE_EDIT_7 = "admin_price_edit_7"
CB_ADMIN_PRICE_EDIT_30 = "admin_price_edit_30"
CB_ADMIN_PRICE_EDIT_90 = "admin_price_edit_90"
CB_ADMIN_PRICE_SAVE = "admin_price_save"
CB_ADMIN_PRICE_CANCEL = "admin_price_cancel"
CB_ADMIN_REFERRALS = "a:rf"
CB_ADMIN_HEALTH = "a:hl"

CB_ADMIN_BACK_MAIN = "a:bk:m"
CB_ADMIN_REFRESH_REFERRALS = "a:rf:r"
CB_ADMIN_REFRESH_HEALTH = "a:rf:h"

CB_BROADCAST_CONFIRM = "broadcast_confirm"
CB_BROADCAST_CANCEL = "broadcast_cancel"

CB_ADMIN_USERS_PAGE_PREFIX = "admin_users_page_"
CB_ADMIN_MANAGE_USER_PREFIX = "admin_manage_user_"
CB_ADMIN_ADD_DAYS_PREFIX = "admin_add_days_"
CB_ADMIN_REVOKE_PREFIX = "admin_revoke_"
CB_ADMIN_DELETE_PREFIX = "admin_delete_"
CB_ADMIN_RETRY_ACTIVATION_PREFIX = "admin_retry_activation_"
CB_ADMIN_DEVICE_DELETE_PREFIX = "admin_device_delete_"
CB_ADMIN_DEVICE_REISSUE_PREFIX = "admin_device_reissue_"

CB_CONFIRM_REVOKE = "confirm_revoke"
CB_CANCEL_REVOKE = "cancel_revoke"
CB_CONFIRM_DELETE_USER = "confirm_delete_user"
CB_CANCEL_DELETE_USER = "cancel_delete_user"
CB_CONFIRM_DEVICE_DELETE = "confirm_device_delete"
CB_CANCEL_DEVICE_DELETE = "cancel_device_delete"
CB_CONFIRM_DEVICE_REISSUE = "confirm_device_reissue"
CB_CANCEL_DEVICE_REISSUE = "cancel_device_reissue"
def is_admin_callback_data(data: str | None) -> bool:
    return bool(data and data.startswith(ADMIN_CALLBACK_PREFIX))


def is_user_config_callback_data(data: str | None) -> bool:
    return bool(data and data.startswith(USER_CONFIG_CALLBACK_PREFIX))
